import { Capacitor } from "@capacitor/core";

// Analytics context: the dimensions attached to every event. Detected once on
// the client; safe to call during SSR (returns "unknown"/defaults).

export type Platform = "android" | "web" | "pwa" | "unknown";
export type AppSurface =
  | "native_shell"
  | "mobile_web"
  | "desktop_web"
  | "installed_pwa"
  | "browser_pwa"
  | "unknown";
export type AppEnvironment = "production" | "staging" | "development" | "test";

export interface AnalyticsContext {
  platform: Platform;
  app_surface: AppSurface;
  app_version?: string;
  build_number?: string;
  environment: AppEnvironment;
  locale?: string;
  timezone?: string;
  anonymous_id: string;
  session_id: string;
  user_id?: string;
}

const ANON_KEY = "eh_anon_id";
const SESSION_KEY = "eh_session_id";
const LS_APP_VERSION = "eh_app_version";
const LS_BUILD_NUMBER = "eh_build_number";
const INSTALL_FLAG = "eh_installed";

let currentUserId: string | undefined;
let cachedAppVersion: string | undefined;
let cachedBuildNumber: string | undefined;

function hasWindow(): boolean {
  return typeof window !== "undefined";
}

function isStandaloneDisplay(): boolean {
  if (!hasWindow()) return false;
  try {
    // iOS Safari exposes navigator.standalone; others use display-mode.
    const nav = navigator as Navigator & { standalone?: boolean };
    return (
      window.matchMedia?.("(display-mode: standalone)")?.matches === true ||
      window.matchMedia?.("(display-mode: fullscreen)")?.matches === true ||
      nav.standalone === true
    );
  } catch {
    return false;
  }
}

function isMobileUA(): boolean {
  if (!hasWindow()) return false;
  return /Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent || "");
}

export function detectPlatform(): Platform {
  if (!hasWindow()) return "unknown";
  if (Capacitor.isNativePlatform()) {
    return Capacitor.getPlatform() === "android" ? "android" : "unknown";
  }
  if (isStandaloneDisplay()) return "pwa";
  return "web";
}

export function detectAppSurface(): AppSurface {
  if (!hasWindow()) return "unknown";
  if (Capacitor.isNativePlatform()) return "native_shell";
  if (isStandaloneDisplay()) {
    return "installed_pwa";
  }
  return isMobileUA() ? "mobile_web" : "desktop_web";
}

export function detectEnvironment(): AppEnvironment {
  const explicit = process.env.NEXT_PUBLIC_APP_ENV as AppEnvironment | undefined;
  if (explicit) return explicit;
  if (process.env.NODE_ENV === "test") return "test";
  if (process.env.NODE_ENV === "development") return "development";
  return "production";
}

function readLocalStorage(key: string): string | null {
  try {
    return hasWindow() ? window.localStorage.getItem(key) : null;
  } catch {
    return null;
  }
}

function writeLocalStorage(key: string, value: string): void {
  try {
    if (hasWindow()) window.localStorage.setItem(key, value);
  } catch {
    /* storage may be unavailable (private mode) — ignore */
  }
}

function uuid(): string {
  try {
    if (hasWindow() && typeof crypto !== "undefined" && crypto.randomUUID) {
      return crypto.randomUUID();
    }
  } catch {
    /* fall through */
  }
  return `eh-${Date.now()}-${Math.random().toString(36).slice(2)}`;
}

// anonymous_id: persistent across sessions and across logout. NOT cleared on
// resetIdentity — it survives so the same visitor/install keeps one thread.
export function getAnonymousId(): string {
  let id = readLocalStorage(ANON_KEY);
  if (!id) {
    id = uuid();
    writeLocalStorage(ANON_KEY, id);
  }
  return id;
}

// session_id: one per app/tab session; regenerated by startAnalyticsSession
// (e.g. on native resume or a fresh web session).
export function getSessionId(): string {
  try {
    if (hasWindow()) {
      let id = window.sessionStorage.getItem(SESSION_KEY);
      if (!id) {
        id = uuid();
        window.sessionStorage.setItem(SESSION_KEY, id);
      }
      return id;
    }
  } catch {
    /* fall through to volatile id */
  }
  return uuid();
}

export function startAnalyticsSession(): string {
  const id = uuid();
  try {
    if (hasWindow()) window.sessionStorage.setItem(SESSION_KEY, id);
  } catch {
    /* ignore */
  }
  return id;
}

export function setUserId(userId: string | undefined): void {
  currentUserId = userId ? String(userId) : undefined;
}

export function getUserId(): string | undefined {
  return currentUserId;
}

// One-time-per-install flag used by the native lifecycle (app_first_open).
export function markInstalledOnce(): boolean {
  if (readLocalStorage(INSTALL_FLAG)) return false;
  writeLocalStorage(INSTALL_FLAG, new Date().toISOString());
  return true;
}

// Returns the previously stored app version and records the current one, so the
// lifecycle layer can detect an app_updated transition.
export function readAndStoreAppVersion(version?: string, build?: string): {
  previousVersion: string | null;
} {
  const previousVersion = readLocalStorage(LS_APP_VERSION);
  if (version) writeLocalStorage(LS_APP_VERSION, version);
  if (build) writeLocalStorage(LS_BUILD_NUMBER, build);
  return { previousVersion };
}

export function setAppVersion(version?: string, build?: string): void {
  if (version) cachedAppVersion = version;
  if (build) cachedBuildNumber = build;
}

function getLocale(): string | undefined {
  try {
    return hasWindow() ? navigator.language : undefined;
  } catch {
    return undefined;
  }
}

function getTimezone(): string | undefined {
  try {
    return Intl.DateTimeFormat().resolvedOptions().timeZone;
  } catch {
    return undefined;
  }
}

export function getAnalyticsContext(): AnalyticsContext {
  return {
    platform: detectPlatform(),
    app_surface: detectAppSurface(),
    app_version: cachedAppVersion ?? readLocalStorage(LS_APP_VERSION) ?? undefined,
    build_number: cachedBuildNumber ?? readLocalStorage(LS_BUILD_NUMBER) ?? undefined,
    environment: detectEnvironment(),
    locale: getLocale(),
    timezone: getTimezone(),
    anonymous_id: getAnonymousId(),
    session_id: getSessionId(),
    user_id: currentUserId,
  };
}
