class AddCoreExercises < ActiveRecord::Migration[8.1]
  def up
    core_exercises = [
      {
        name: "Crunch Abdominal",
        name_en: "Crunch",
        description: "Exercício clássico para abdômen superior. Eleve os ombros do chão contraindo o reto abdominal.",
        instructions: "Deite de costas com joelhos dobrados. Eleve os ombros contraindo o abdômen. Desça lentamente.",
        exercise_type: "musculacao",
        equipment_type: "bodyweight",
        muscle_group: "core",
        difficulty_level: "beginner",
        home_compatible: true,
        source_dataset: "manual_core_2026",
      },
      {
        name: "Sit-up",
        name_en: "Sit-up",
        description: "Movimento completo de elevação do tronco, trabalhando abdômen e flexores do quadril.",
        instructions: "Deite com joelhos dobrados. Eleve o tronco até sentar, usando o abdômen. Desça controlado.",
        exercise_type: "musculacao",
        equipment_type: "bodyweight",
        muscle_group: "core",
        difficulty_level: "beginner",
        home_compatible: true,
        source_dataset: "manual_core_2026",
      },
      {
        name: "Elevação de Pernas",
        name_en: "Leg Raise",
        description: "Foco no abdômen inferior. Eleve as pernas mantendo-as retas enquanto mantém a lombar no chão.",
        instructions: "Deite com pernas estendidas. Eleve as pernas a 90° sem arquear a lombar. Desça devagar.",
        exercise_type: "musculacao",
        equipment_type: "bodyweight",
        muscle_group: "core",
        difficulty_level: "intermediate",
        home_compatible: true,
        source_dataset: "manual_core_2026",
      },
      {
        name: "Russian Twist",
        name_en: "Russian Twist",
        description: "Rotação do tronco para trabalhar os oblíquos. Pode ser realizado com ou sem peso.",
        instructions: "Sente com joelhos dobrados e tronco inclinado. Gire o tronco alternando os lados de forma controlada.",
        exercise_type: "musculacao",
        equipment_type: "bodyweight",
        muscle_group: "core",
        difficulty_level: "intermediate",
        home_compatible: true,
        source_dataset: "manual_core_2026",
      },
      {
        name: "Prancha Lateral",
        name_en: "Side Plank",
        description: "Isometria lateral que trabalha os oblíquos e o estabilizador lateral do core.",
        instructions: "Apoie-se em um cotovelo e no lado dos pés. Mantenha o quadril elevado e o corpo alinhado. Segure.",
        exercise_type: "timed",
        equipment_type: "bodyweight",
        muscle_group: "core",
        difficulty_level: "intermediate",
        home_compatible: true,
        source_dataset: "manual_core_2026",
      },
      {
        name: "Superman",
        name_en: "Superman",
        description: "Extensão simultânea de braços e pernas para fortalecer a lombar e o ereto espinhal.",
        instructions: "Deite de bruços. Eleve simultaneamente braços e pernas do chão. Segure brevemente e desça.",
        exercise_type: "musculacao",
        equipment_type: "bodyweight",
        muscle_group: "core",
        difficulty_level: "beginner",
        home_compatible: true,
        source_dataset: "manual_core_2026",
      },
      {
        name: "Dead Bug",
        name_en: "Dead Bug",
        description: "Exercício de controle motor do core. Alterna extensão de braço e perna oposta sem mover a lombar.",
        instructions: "Deite de costas com braços estendidos e pernas a 90°. Estenda um braço e a perna oposta sem arquear. Alterne.",
        exercise_type: "musculacao",
        equipment_type: "bodyweight",
        muscle_group: "core",
        difficulty_level: "intermediate",
        home_compatible: true,
        source_dataset: "manual_core_2026",
      },
      {
        name: "Hollow Body Hold",
        name_en: "Hollow Body Hold",
        description: "Isometria de core total. Mantém braços e pernas elevados com abdômen contraído ao máximo.",
        instructions: "Deite de costas. Eleve levemente cabeça, ombros, braços e pernas do chão. Pressione a lombar no chão. Segure.",
        exercise_type: "timed",
        equipment_type: "bodyweight",
        muscle_group: "core",
        difficulty_level: "intermediate",
        home_compatible: true,
        source_dataset: "manual_core_2026",
      },
      {
        name: "V-Up",
        name_en: "V-Up",
        description: "Exercício avançado que eleva simultaneamente tronco e pernas, formando um V.",
        instructions: "Deite com braços estendidos acima da cabeça. Eleve tronco e pernas ao mesmo tempo tocando os pés. Desça controlado.",
        exercise_type: "musculacao",
        equipment_type: "bodyweight",
        muscle_group: "core",
        difficulty_level: "advanced",
        home_compatible: true,
        source_dataset: "manual_core_2026",
      },
      {
        name: "Oblíquo com Rotação",
        name_en: "Oblique Crunch",
        description: "Crunch com rotação para trabalhar os oblíquos de forma isolada.",
        instructions: "Deite com mãos atrás da cabeça. Eleve e gire levando cotovelo ao joelho oposto. Alterne os lados.",
        exercise_type: "musculacao",
        equipment_type: "bodyweight",
        muscle_group: "core",
        difficulty_level: "beginner",
        home_compatible: true,
        source_dataset: "manual_core_2026",
      },
      {
        name: "Prancha com Alcance",
        name_en: "Plank Reach",
        description: "Variação da prancha com extensão de um braço à frente, aumentando o desafio de estabilidade.",
        instructions: "Em posição de prancha alta. Eleve alternadamente cada braço à frente mantendo o quadril estável.",
        exercise_type: "musculacao",
        equipment_type: "bodyweight",
        muscle_group: "core",
        difficulty_level: "intermediate",
        home_compatible: true,
        source_dataset: "manual_core_2026",
      },
      {
        name: "Hip Bridge",
        name_en: "Hip Bridge",
        description: "Ponte de quadril focada em glúteos e core lombar. Levanta o quadril mantendo a contração.",
        instructions: "Deite com joelhos dobrados. Eleve o quadril contraindo glúteos e abdômen. Segure no topo e desça.",
        exercise_type: "musculacao",
        equipment_type: "bodyweight",
        muscle_group: "core",
        difficulty_level: "beginner",
        home_compatible: true,
        source_dataset: "manual_core_2026",
      },
      {
        name: "Bicicleta Alternada",
        name_en: "Bicycle Crunch",
        description: "Pedala imaginária alternando rotação de cotovelo ao joelho oposto, ativando oblíquos e reto.",
        instructions: "Deite com mãos atrás da cabeça. Leve cotovelo ao joelho oposto em movimento de pedalada alternado.",
        exercise_type: "musculacao",
        equipment_type: "bodyweight",
        muscle_group: "core",
        difficulty_level: "beginner",
        home_compatible: true,
        source_dataset: "manual_core_2026",
      },
      {
        name: "Abdominal com Elevação de Quadril",
        name_en: "Reverse Crunch",
        description: "Crunch reverso que eleva o quadril em direção ao teto para trabalhar o abdômen inferior.",
        instructions: "Deite com pernas dobradas. Eleve o quadril contraindo o abdômen inferior. Desça lentamente.",
        exercise_type: "musculacao",
        equipment_type: "bodyweight",
        muscle_group: "core",
        difficulty_level: "beginner",
        home_compatible: true,
        source_dataset: "manual_core_2026",
      },
      {
        name: "Caminhada do Urso",
        name_en: "Bear Crawl",
        description: "Movimento de engatinhar com joelhos suspensos que ativa o core e a coordenação motora.",
        instructions: "Em quatro apoios com joelhos a ~5cm do chão. Mova braço e perna opostos alternadamente mantendo costas retas.",
        exercise_type: "funcional",
        equipment_type: "bodyweight",
        muscle_group: "core",
        difficulty_level: "intermediate",
        home_compatible: true,
        source_dataset: "manual_core_2026",
      },
    ]

    core_exercises.each do |attrs|
      next if Exercise.exists?(name: attrs[:name])
      Exercise.create!(attrs)
    end
  end

  def down
    Exercise.where(source_dataset: "manual_core_2026").destroy_all
  end
end
