default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: "<%= ENV.fetch("DB_PASSWORD", "") %>"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: easy_health_development

test:
  <<: *default
  database: easy_health_test

production:
  <<: *default
  database: easy_health_production
  password: "<%= ENV["DB_PASSWORD"] %>"
