module WorkoutIntelligence
  # Curated metadata for the exercises most likely to be selected by the
  # generator (the exercises explicitly cited in the audit + the legacy
  # curated list in lib/tasks/exercises.rake::SLUG_MAP). Not exhaustive —
  # exercises outside this list fall back to TechnicalLevelPolicy's
  # name-pattern classifier. Run `rails workout_intelligence:enrich_exercise_metadata`
  # to apply these records; unmatched names are logged for manual review.
  module ExerciseEnrichmentSeed
    RECORDS = [
      # ---- Mandatory (cited in the audit) ----
      { name: "Muscle Up", technical_complexity: "high", risk_level: "high", calisthenics_skill: "advanced",
        movement_pattern: "pull", compound: true, requires_bodyweight_strength: true,
        objective_tags: %w[strength hypertrophy], style_tags: %w[calisthenics] },
      { name: "Barra Fixa", technical_complexity: "medium", risk_level: "medium", calisthenics_skill: "basic",
        movement_pattern: "pull", compound: true, requires_bodyweight_strength: true,
        objective_tags: %w[strength hypertrophy], style_tags: %w[calisthenics traditional_strength] },
      { name: "Levantamento Terra", technical_complexity: "high", risk_level: "high", calisthenics_skill: "none",
        movement_pattern: "hinge", compound: true, requires_barbell_skill: true,
        objective_tags: %w[strength hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Agachamento", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "squat", compound: true,
        objective_tags: %w[strength hypertrophy conditioning health], style_tags: %w[calisthenics functional] },
      { name: "Leg Press", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "squat", compound: true,
        objective_tags: %w[strength hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Maquina De Abducao De Quadril", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "isolation", compound: false,
        objective_tags: %w[hypertrophy conditioning], style_tags: %w[traditional_strength] },
      { name: "Face Pull", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "pull", compound: false,
        objective_tags: %w[hypertrophy health], style_tags: %w[traditional_strength] },
      { name: "Rosca Martelo", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "isolation", compound: false,
        objective_tags: %w[hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Triceps No Banco", technical_complexity: "medium", risk_level: "medium", calisthenics_skill: "basic",
        movement_pattern: "push", compound: false, requires_bodyweight_strength: true,
        objective_tags: %w[hypertrophy], style_tags: %w[calisthenics traditional_strength] },
      { name: "Anilha Press", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "isolation", compound: false,
        objective_tags: %w[hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Cross Over Polia Alta", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "isolation", compound: false,
        objective_tags: %w[hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Extensao Concentrada Com Cabo No Joelho", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "isolation", compound: false,
        objective_tags: %w[hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Circulos De Braco Com Pesos", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "isolation", compound: false,
        objective_tags: %w[mobility health], style_tags: %w[mobility traditional_strength] },
      { name: "Flexao De Pulso Neutra Sentado Com Halteres", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "isolation", compound: false,
        objective_tags: %w[hypertrophy health], style_tags: %w[traditional_strength] },

      # ---- Regression targets (safe alternatives resolved by RegressionMap) ----
      { name: "Barra Fixa Assistida", technical_complexity: "low", risk_level: "low", calisthenics_skill: "basic",
        movement_pattern: "pull", compound: true,
        objective_tags: %w[strength hypertrophy health], style_tags: %w[calisthenics] },
      { name: "Remada Invertida", technical_complexity: "low", risk_level: "low", calisthenics_skill: "basic",
        movement_pattern: "pull", compound: true, requires_bodyweight_strength: true,
        objective_tags: %w[strength hypertrophy], style_tags: %w[calisthenics] },
      { name: "Levantamento Terra Romeno Com Halteres", technical_complexity: "medium", risk_level: "medium", calisthenics_skill: "none",
        movement_pattern: "hinge", compound: true,
        objective_tags: %w[strength hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Agachamento Barra", technical_complexity: "high", risk_level: "medium", calisthenics_skill: "none",
        movement_pattern: "squat", compound: true, requires_barbell_skill: true,
        objective_tags: %w[strength hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Agachamento Frontal", technical_complexity: "high", risk_level: "medium", calisthenics_skill: "none",
        movement_pattern: "squat", compound: true, requires_barbell_skill: true,
        objective_tags: %w[strength hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Agachamento Goblet Com Haltere", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "squat", compound: true,
        objective_tags: %w[strength hypertrophy conditioning health], style_tags: %w[traditional_strength functional] },
      { name: "Triceps Pulley Corda", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "isolation", compound: false,
        objective_tags: %w[hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Puxada Alta Com Triangulo", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "pull", compound: true,
        objective_tags: %w[hypertrophy strength], style_tags: %w[traditional_strength] },
      { name: "Cadeira Extensora", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "isolation", compound: false,
        objective_tags: %w[hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Cadeira Flexora", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "isolation", compound: false,
        objective_tags: %w[hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Mesa Flexora", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "isolation", compound: false,
        objective_tags: %w[hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Remada Curvada Com Barra", technical_complexity: "medium", risk_level: "medium", calisthenics_skill: "none",
        movement_pattern: "pull", compound: true, requires_barbell_skill: true,
        objective_tags: %w[strength hypertrophy], style_tags: %w[traditional_strength] },

      # ---- Legacy curated set (lib/tasks/exercises.rake::SLUG_MAP) ----
      { name: "Flexao De Braco", technical_complexity: "low", risk_level: "low", calisthenics_skill: "basic",
        movement_pattern: "push", compound: true,
        objective_tags: %w[health hypertrophy conditioning], style_tags: %w[calisthenics] },
      { name: "Supino", technical_complexity: "medium", risk_level: "medium", calisthenics_skill: "none",
        movement_pattern: "push", compound: true, requires_barbell_skill: true,
        objective_tags: %w[strength hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Remada Curvada", technical_complexity: "medium", risk_level: "medium", calisthenics_skill: "none",
        movement_pattern: "pull", compound: true, requires_barbell_skill: true,
        objective_tags: %w[strength hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Desenvolvimento", technical_complexity: "medium", risk_level: "medium", calisthenics_skill: "none",
        movement_pattern: "push", compound: true, requires_barbell_skill: true,
        objective_tags: %w[strength hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Elevacao Lateral", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "isolation", compound: false,
        objective_tags: %w[hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Rosca Direta", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "isolation", compound: false,
        objective_tags: %w[hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Mergulho No Banco", technical_complexity: "medium", risk_level: "medium", calisthenics_skill: "basic",
        movement_pattern: "push", compound: false, requires_bodyweight_strength: true,
        objective_tags: %w[hypertrophy], style_tags: %w[calisthenics] },
      { name: "Triceps Frances", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "isolation", compound: false,
        objective_tags: %w[hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Avanco", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "lunge", compound: true, unilateral: true,
        objective_tags: %w[strength hypertrophy conditioning], style_tags: %w[traditional_strength functional] },
      { name: "Panturrilha Em Pe", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "isolation", compound: false,
        objective_tags: %w[hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Elevacao Pelvica", technical_complexity: "medium", risk_level: "medium", calisthenics_skill: "none",
        movement_pattern: "hinge", compound: true,
        objective_tags: %w[strength hypertrophy], style_tags: %w[traditional_strength] },
      { name: "Ponte Unilateral", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "hinge", compound: true, unilateral: true,
        objective_tags: %w[health hypertrophy], style_tags: %w[functional calisthenics] },
      { name: "Afundo Reverso", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "lunge", compound: true, unilateral: true,
        objective_tags: %w[strength hypertrophy conditioning], style_tags: %w[traditional_strength functional] },
      { name: "Prancha", technical_complexity: "low", risk_level: "low", calisthenics_skill: "basic",
        movement_pattern: "isolation", compound: false,
        objective_tags: %w[health mobility conditioning], style_tags: %w[calisthenics mobility] },
      { name: "Abdominal", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "isolation", compound: false,
        objective_tags: %w[health hypertrophy], style_tags: %w[calisthenics] },
      { name: "Abdominal Bicicleta", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "isolation", compound: false,
        objective_tags: %w[conditioning health], style_tags: %w[calisthenics] },
      { name: "Pular Corda", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "locomotion", compound: false,
        objective_tags: %w[conditioning], style_tags: %w[cardio] },
      { name: "Remo Ergometro", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "locomotion", compound: true,
        objective_tags: %w[conditioning], style_tags: %w[cardio] },
      { name: "Bicicleta", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "locomotion", compound: false,
        objective_tags: %w[conditioning], style_tags: %w[cardio] },
      { name: "Eliptico", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "locomotion", compound: false,
        objective_tags: %w[conditioning], style_tags: %w[cardio] },
      { name: "Corrida Esteira", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "locomotion", compound: false,
        objective_tags: %w[conditioning], style_tags: %w[cardio] },
      { name: "Corrida Rua", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "locomotion", compound: false,
        objective_tags: %w[conditioning], style_tags: %w[cardio] },
      { name: "Burpee", technical_complexity: "medium", risk_level: "medium", calisthenics_skill: "basic",
        movement_pattern: "locomotion", compound: true, requires_bodyweight_strength: true,
        objective_tags: %w[conditioning strength], style_tags: %w[calisthenics cardio] },
      { name: "Salto Na Caixa", technical_complexity: "medium", risk_level: "medium", calisthenics_skill: "basic",
        movement_pattern: "squat", compound: true,
        objective_tags: %w[conditioning strength], style_tags: %w[functional cardio] },
      { name: "Escalador", technical_complexity: "low", risk_level: "low", calisthenics_skill: "basic",
        movement_pattern: "isolation", compound: false,
        objective_tags: %w[conditioning], style_tags: %w[calisthenics cardio] },
      { name: "Agachamento Com Salto", technical_complexity: "medium", risk_level: "medium", calisthenics_skill: "basic",
        movement_pattern: "squat", compound: true,
        objective_tags: %w[conditioning strength], style_tags: %w[calisthenics cardio] },
      { name: "Polichinelo", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "locomotion", compound: false,
        objective_tags: %w[conditioning], style_tags: %w[cardio] },
      { name: "Agachamento Isometrico", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "squat", compound: true,
        objective_tags: %w[health conditioning], style_tags: %w[calisthenics] },
      { name: "Swing Com Kettlebell", technical_complexity: "medium", risk_level: "medium", calisthenics_skill: "basic",
        movement_pattern: "hinge", compound: true,
        objective_tags: %w[strength conditioning], style_tags: %w[functional] },
      { name: "Remada No Trx", technical_complexity: "medium", risk_level: "medium", calisthenics_skill: "basic",
        movement_pattern: "pull", compound: true, requires_bodyweight_strength: true,
        objective_tags: %w[strength hypertrophy], style_tags: %w[functional calisthenics] },
      { name: "Corda Naval", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "isolation", compound: false,
        objective_tags: %w[conditioning], style_tags: %w[functional cardio] },
      { name: "Caminhada Moderada", technical_complexity: "low", risk_level: "low", calisthenics_skill: "none",
        movement_pattern: "locomotion", compound: false,
        objective_tags: %w[health conditioning], style_tags: %w[cardio mobility] },
    ].freeze
  end
end
