source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "bcrypt", "~> 3.1.7"
gem "devise"
gem "rack-cors"
gem "rack-attack"
gem "image_processing", "~> 1.2"

gem "sentry-ruby"
gem "sentry-rails"

gem "anthropic", "~> 0.3"
gem "ruby-openai"
gem "stripe", "~> 13.0"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rspec-rails"
  gem "factory_bot_rails"
end
